### ISSUE TITLE
Zapper timer and PIP

### ISSUE THREAD

**Issue by sysofadown88** [BlackHole/enigma2#107]
Hi I stopped using your images since you introduce this problem in OBH 4.4 which when you set zap timer for schedule events like movie or tvshow or football game it suppose to exit from current tv-channel service to tv-channel service that you set-up zapper time to it.
but instead it's stay on current tv-channel service and with PIP black window on top of the screen similar to attached photo
has this problem been fixed in OBH 5.1or at least is there something I can change in recording setting to fix it? 
others OE-images like oatv never had this strange problem.
![IMG_20221113_145846](https://user-images.githubusercontent.com/116835717/201523857-794f938e-6b73-4936-87fa-013e01f3eb3c.jpg)

**Comment by Ev0-BH** [comment]
Update your image and check
