### ISSUE TITLE
Hide buffering message on IPTV?

### ISSUE THREAD

**Issue by benevenstanciano** [BlackHole/enigma2#110]
Hi,
For some reason when watching IPTV channels I am now seeing a constant “buffering 99%” message in the top left corner. I have no buffering issues, but the numbers are changing and it’s annoying. Is there any way to remove this?

**Comment by Ev0-BH** [comment]
Update your image

**Comment by benevenstanciano** [comment]
I've updated the image and now I am stuck on the boot screen. I did a backup, but I don't know how to revert. Should I reflash the receiver? Where can I download the latest version to USB?
