### ISSUE TITLE
'new_ePoint', argument 2 of type 'int' skin issue

### ISSUE THREAD

**Issue by iMuaad** [BlackHole/enigma2#111]
The skin MX_Sline-Black work smoothly, except when ask for DreamSatPanel account info

<160722.7857> 13:45:09.7272 [Skin] Parsing embedded skin '<embedded-in-DreamSatMessageBox>'.
<160722.7872> 13:45:09.7287 [Skin] Processing screen '<embedded-in-DreamSatMessageBox>', position=(510, 535), size=(900 x 10) for module 'DreamSatMessageBox'.
<160722.7980> 13:45:09.7395 Traceback (most recent call last):
<160722.7981> 13:45:09.7396   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
<160722.7999> 13:45:09.7414   File "launcher.py", line 161, in launcher.LinuxsatLauncher.ok
<160722.8003> 13:45:09.7418   File "/usr/lib/enigma2/python/StartEnigma.py", line 314, in open
<160722.8013> 13:45:09.7428     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
<160722.8013> 13:45:09.7428   File "/usr/lib/enigma2/python/StartEnigma.py", line 251, in instantiateDialog
<160722.8019> 13:45:09.7434     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
<160722.8020> 13:45:09.7435   File "/usr/lib/enigma2/python/StartEnigma.py", line 281, in doInstantiateDialog
<160722.8025> 13:45:09.7440     dlg.applySkin()
<160722.8026> 13:45:09.7441   File "/usr/lib/enigma2/python/Screens/Screen.py", line 246, in applySkin
<160722.8029> 13:45:09.7444   File "/usr/lib/enigma2/python/Screens/Screen.py", line 276, in createGUIScreen
<160722.8032> 13:45:09.7447   File "MessageBox.py", line 145, in MessageBox.DreamSatMessageBox.layoutFinished
<160722.8035> 13:45:09.7450   File "/usr/lib/enigma2/python/enigma.py", line 1215, in __init__
<160722.8038> 13:45:09.7453 TypeError: in method 'new_ePoint', argument 2 of type 'int'
Additional information:
Wrong number or type of arguments for overloaded function 'new_ePoint'.
  Possible C/C++ prototypes are:
    ePoint::ePoint()
    ePoint::ePoint(int,int)
<160722.8038> 13:45:09.7453 
<160722.8039> 13:45:09.7454 [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xae1be208>>,('DreamSatPanelActions', 'ok')) failed)

**Comment by Ev0-BH** [comment]
What image are you using ?

**Comment by iMuaad** [comment]
It was noted since openBH 5.1.011 and now using openBH 5.1.012 still there

I can send the crash log and the skin used.

**Comment by Ev0-BH** [comment]
Ask the author to fix the plugin for OpenBh 5.1

**Comment by iMuaad** [comment]
I already asked this,
Said no issue with the plugin 
The issue is with this new version of the image since they have change some parameters.

**Comment by Ev0-BH** [comment]
So the plugin worked with our image, now it doesn't.

Plugin needs to be updated not the image updated to work with the plugin.

**Comment by fairbird** [comment]
@Ev0-BH 
The issue from E2 not from plugin ...
Plugin just want to open MessageBox screen to print info details nothings more ...
Plugin works find on other images such as OpenaTV, OpenPLi, Pure2 (Py3) ..etc 
That issue happens just on OpenBH ...

Thank you

**Comment by Ev0-BH** [comment]
Have you tried using different skins ?

Maybe try with the default skin MX Slim-Line NP

**Comment by iMuaad** [comment]
Already tried it
and tried different skins different sources all of them support PY3

All same issue

**Comment by Huevos** [comment]
Where is the plugin repo? 100% this is a skin error.

**Comment by iMuaad** [comment]
This is the code to install

wget -q "--no-check-certificate" http://ipkinstall.ath.cx/ipk-install/DreamSatPanel/installer.sh  -O - | /bin/sh

**Comment by Huevos** [comment]
> This is the code to install
> 
> wget -q "--no-check-certificate" http://ipkinstall.ath.cx/ipk-install/DreamSatPanel/installer.sh -O - | /bin/sh

Are you taking the piss?

**Comment by Ev0-BH** [comment]
Really not sure how you are expecting us to be able to fix anything.

The plugin is .pyc and .so so no idea what the code is asking for.

Ontop of that, you have to pay for activation (I assume, otherwise why would you need an activation code), again not something we are going to do, to try and fix something for you.
