### ISSUE TITLE
Change audio channels not work

### ISSUE THREAD

**Issue by popking159** [BlackHole/enigma2#125]
![1705759515541](https://github.com/BlackHole/enigma2/assets/47087407/cc34e487-ca12-45c6-98ab-002ae34265b4)
This feed channel contains 4 audio tracks , each track has 2 overlap audio channels , when changing stereo to left or right to select only one audio channel , nothing happens.

Maybe there's a problem in drivers , 
Box : Novaler 4k se , Novaler 4k pro

**Comment by Ev0-BH** [comment]
1st of all it's a feed, they don't always follow correct standards with the audio broadcast.

2nd we don't support Novaler 4K SE, so if you have the issue with that box, then you are not using official image.
