### ISSUE TITLE
SNRdB problem 

### ISSUE THREAD

**Issue by popking159** [BlackHole/enigma2#129]
My box is Novalerpro 
The problem is SNRdB not working , even if I choose " swap SNR in % with SNR in db " the infobar showing SNR in %  .

**Comment by dpeddi** [comment]
Hello,
I can't replicate it seems ok to me... novaler4kpro:

![image](https://github.com/BlackHole/enigma2/assets/1086815/7af5b036-9906-4118-b5be-0f84e404e903)

swap snr inactive:
![image](https://github.com/BlackHole/enigma2/assets/1086815/05bb4a47-370d-49fc-87cd-03292faf4e1d)
![image](https://github.com/BlackHole/enigma2/assets/1086815/1480b0b0-23dd-4f0f-8f1f-7bd13549ca81)

swap snr active:
![image](https://github.com/BlackHole/enigma2/assets/1086815/2732cd83-4496-438b-9cca-55d61b5883ad)
![image](https://github.com/BlackHole/enigma2/assets/1086815/fb2df57c-bdc1-412c-9a72-cdd5cfcd9298)

Regards

**Comment by popking159** [comment]
![IMG_20240429_150444](https://github.com/BlackHole/enigma2/assets/47087407/379afbc3-ffa5-45ca-8361-e65279ed1646)
![IMG_20240429_150505](https://github.com/BlackHole/enigma2/assets/47087407/27b69d7b-8994-42fc-bf21-87ba66579752)

Which recovery do you use ?
@dpeddi

**Comment by dpeddi** [comment]
why you are asking about the recovery?

**Comment by popking159** [comment]
@dpeddi 
I installed a fresh one and don't install any plugin or skin , and the same problem .
I am using recovery 353 , I ask about it as it may be the problem , this problem was present in openatv 7.4 but it is normal now , and the same problem was present 2 or 3 months ago and I remember that I solved this with replacing the converter responsible for this .
But you are saying that it works normal with you on OBH 5.4.0.3 , so I guess the problem is in recovery .

**Comment by Ev0-BH** [comment]
I also have no issue with Obh 5.4.003, I just checked and on 1 channel it shows 66% signal or 13.2db (same channel on another box using the same lnb, shows 80% signal, so the level could do with a tweak, but other than that, I don't see any issue).

**Comment by Ev0-BH** [comment]
My box has r353 on it too

**Comment by popking159** [comment]
> I also have no issue with Obh 5.4.003, I just checked and on 1 channel it shows 66% signal or 13.2db (same channel on another box using the same lnb, shows 80% signal, so the level could do with a tweak, but other than that, I don't see any issue).

The level needs a tweaks of course, but it is not my problem here , 
My problem is the option "swap SNR with SNRdB" is not effective, the yes or no options are showing the same thing which is % and no db at all .

**Comment by popking159** [comment]
![1714395562795](https://github.com/BlackHole/enigma2/assets/47087407/d1f0fd7a-c15d-4614-95f1-a751a30c8bcf)

Even here in positioner screen and signal finder , no db only %

**Comment by popking159** [comment]
![1714395725499](https://github.com/BlackHole/enigma2/assets/47087407/ae44bdab-89ae-4148-b46f-6eea26af56e3)
The db appears only before signal lock , once locked % appears

**Comment by Ev0-BH** [comment]
![screenshot_20240429140438](https://github.com/BlackHole/enigma2/assets/3958411/d00c7cd3-bcaa-453f-9f75-15f56a46e9a9)

![screenshot_20240429141114](https://github.com/BlackHole/enigma2/assets/3958411/47ca2856-84bb-4f25-b460-215b5dcd8442)

**Comment by popking159** [comment]
@Ev0-BH 
Maybe the problem is in the skin ?

**Comment by Ev0-BH** [comment]
I'm thinking no.

![screenshot_20240429142834](https://github.com/BlackHole/enigma2/assets/3958411/e6a9aed2-f549-460c-b589-085db3e37ace)

![screenshot_20240429142858](https://github.com/BlackHole/enigma2/assets/3958411/07023ae7-028c-430a-a9a7-e891510cd6dc)

**Comment by popking159** [comment]
@dpeddi 
@Ev0-BH 
I am very confused , anyway , thanks for help , 
Regards

**Comment by Ev0-BH** [comment]
try a clean reflash, do not install any backup and try again

**Comment by popking159** [comment]
> try a clean reflash, do not install any backup and try again

I did it already , all screenshots are from clean install , no plugins , no skins

**Comment by popking159** [comment]
The problem is not solved yet .
The problem is present only in Novaler pro
The problem is also in openvix
